//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/SampleViewer/Samples/FlightSim/FlightSimControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @FlightSimControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @FlightSimControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""FlightSimControls"",
    ""maps"": [
        {
            ""name"": ""Plane Movement"",
            ""id"": ""15dd230d-c085-44a7-81ef-926d9f37aa5f"",
            ""actions"": [
                {
                    ""name"": ""PitchandRoll"",
                    ""type"": ""Value"",
                    ""id"": ""3d87fa90-5e51-455f-8fd9-26d5b88be985"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accelerate"",
                    ""type"": ""Value"",
                    ""id"": ""cdab6b99-dbf1-4b74-bedb-875b0890dab1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hide Landing Gear"",
                    ""type"": ""Button"",
                    ""id"": ""2a90c672-7bd2-489c-a1da-07fa444a434a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard Acceleration"",
                    ""id"": ""e3c5db3a-a3f2-4938-91f6-1b04adabb9c1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""53e5526d-f8a6-4c66-b97f-2f5287528d8a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""2623e428-f44e-40e5-8643-2636b310211d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""c7b571c4-b5b6-4f60-aa4b-10aafd81d8f5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""7ce3e3f8-2454-44ca-a322-0ceb886a6133"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad Acceleration"",
                    ""id"": ""2a7a0f1e-ac5a-4d59-aa66-216538a57559"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""54ddef46-5fae-404d-9b38-a56e867e693c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""a1b0dbf3-4fe6-481a-ba92-7cd9b7288224"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6a6ba18d-9cca-48f3-813d-6c5edb5dfcb0"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e1d3f329-2e14-489e-a3b8-84ba38556cf2"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard Pitch"",
                    ""id"": ""20b76cf8-e0fb-4f3a-a2bb-51c42cdc5aee"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""e07fa387-577f-4c08-8f84-78a5489832c6"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""8006f329-e53d-4d59-8db3-f2ea85bc572b"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""5c17c81d-44bc-448e-8435-bf3ad06aa18c"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""081c250f-37a8-4981-b5fa-7b41bc27bd5f"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad Pitch"",
                    ""id"": ""0509816b-9724-488c-9da6-26626199ad93"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""00b62bfb-e88b-49fd-a5a7-acbe25001038"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2e95383e-34b0-4da8-8ad2-72c394221fba"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bb0b1672-10bb-4226-9bf3-8be869d2400e"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e0ba8576-31b3-47b2-a2a5-d62a5f022417"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""PitchandRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ee905ef7-69ad-4bf8-801d-c0f0922b64a0"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hide Landing Gear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""227bfce0-3237-427d-aeda-35038a9d1593"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hide Landing Gear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Plane Movement
        m_PlaneMovement = asset.FindActionMap("Plane Movement", throwIfNotFound: true);
        m_PlaneMovement_PitchandRoll = m_PlaneMovement.FindAction("PitchandRoll", throwIfNotFound: true);
        m_PlaneMovement_Accelerate = m_PlaneMovement.FindAction("Accelerate", throwIfNotFound: true);
        m_PlaneMovement_HideLandingGear = m_PlaneMovement.FindAction("Hide Landing Gear", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Plane Movement
    private readonly InputActionMap m_PlaneMovement;
    private IPlaneMovementActions m_PlaneMovementActionsCallbackInterface;
    private readonly InputAction m_PlaneMovement_PitchandRoll;
    private readonly InputAction m_PlaneMovement_Accelerate;
    private readonly InputAction m_PlaneMovement_HideLandingGear;
    public struct PlaneMovementActions
    {
        private @FlightSimControls m_Wrapper;
        public PlaneMovementActions(@FlightSimControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PitchandRoll => m_Wrapper.m_PlaneMovement_PitchandRoll;
        public InputAction @Accelerate => m_Wrapper.m_PlaneMovement_Accelerate;
        public InputAction @HideLandingGear => m_Wrapper.m_PlaneMovement_HideLandingGear;
        public InputActionMap Get() { return m_Wrapper.m_PlaneMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlaneMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlaneMovementActions instance)
        {
            if (m_Wrapper.m_PlaneMovementActionsCallbackInterface != null)
            {
                @PitchandRoll.started -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnPitchandRoll;
                @PitchandRoll.performed -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnPitchandRoll;
                @PitchandRoll.canceled -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnPitchandRoll;
                @Accelerate.started -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnAccelerate;
                @Accelerate.performed -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnAccelerate;
                @Accelerate.canceled -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnAccelerate;
                @HideLandingGear.started -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnHideLandingGear;
                @HideLandingGear.performed -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnHideLandingGear;
                @HideLandingGear.canceled -= m_Wrapper.m_PlaneMovementActionsCallbackInterface.OnHideLandingGear;
            }
            m_Wrapper.m_PlaneMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PitchandRoll.started += instance.OnPitchandRoll;
                @PitchandRoll.performed += instance.OnPitchandRoll;
                @PitchandRoll.canceled += instance.OnPitchandRoll;
                @Accelerate.started += instance.OnAccelerate;
                @Accelerate.performed += instance.OnAccelerate;
                @Accelerate.canceled += instance.OnAccelerate;
                @HideLandingGear.started += instance.OnHideLandingGear;
                @HideLandingGear.performed += instance.OnHideLandingGear;
                @HideLandingGear.canceled += instance.OnHideLandingGear;
            }
        }
    }
    public PlaneMovementActions @PlaneMovement => new PlaneMovementActions(this);
    public interface IPlaneMovementActions
    {
        void OnPitchandRoll(InputAction.CallbackContext context);
        void OnAccelerate(InputAction.CallbackContext context);
        void OnHideLandingGear(InputAction.CallbackContext context);
    }
}
